### ISSUE TITLE
Support video recording

### ISSUE THREAD

**Issue by anselmolsm** [Dronecode/camera-manager#13]

**Comment by rmackay9** [comment]
I'm also very keen on this item.

**Comment by otaviobp** [comment]
Just to let it documented here, these MAVLink messages can be used in order to have video streaming support using MAVLink:
MAV_CMD_VIDEO_START_CAPTURE, MAV_CMD_VIDEO_STOP_CAPTURE, MAV_CMD_REQUEST_CAMERA_CAPTURE_STATUS

**Comment by shakthi-prashanth-m** [comment]
I think https://github.com/Dronecode/camera-manager/pull/157 resolves this.

**Comment by hamishwillee** [comment]
Yes, this can be closed. Streaming was supported for ages, and video saving/capture was delivered by #157. Controlled using MAVLink Camera API messages

Docs updated (really this is just the additional config in the [vidcap](https://hamishwillee.gitbooks.io/camera-manager/content/en/guide/configuration_file.html#vidcap) section of the config file.)
