### ISSUE TITLE
CSD continues to get launched even when invalid conf file passed

### ISSUE THREAD

**Issue by shakthi-prashanth-m** [Dronecode/camera-manager#155]
When I run CSD on [Ubuntu Camera](https://hamishwillee.gitbooks.io/camera-streaming-daemon/content/en/getting_started/quick_start_ubuntu_webcam.html) as below:
```
$ ./csd -v -c samples/config/ubuntu.co   // Wrong config filename
Could not open conf file 'samples/config/ubuntu.co' (No such file or directory)

Found V4L2 camera device video0
v4l2 device :: /dev/video0
Section 'uri' not found and field 'video0' is required.
Camera Definition for device:video0 not found
CameraComponent path:/dev/video0
V4L2 device : /dev/video0
CameraDeviceV4l2 Node: /dev/video0
	Driver name   : ov534
	Card type     : USB Camera-B4.09.24.1
	Bus info      : usb-0000:00:14.0-7
	Driver version: 4.4.98
	Capabilities  : 0x85200001
	Device Caps   : 0x05200001
...
```

Ideally, if the config filename is **invalid**, CSD shouldn't go ahead isn't it ?

As I see below:
https://github.com/intel/camera-streaming-daemon/blob/82bf439afda14be1106cea2042f66e157d641fe8/src/main.cpp#L92-L103

If there's **no such conf** file, then it goes ahead to parse conf files of the `conf_dir` which is `nullptr` when command-line argument **-c** is passed. It should parse only when **-d** option is passed.

In case of
```
$ ./csd -v -c samples/config/ubuntu.co   // Wrong config filename
```
most expected behavior I can think of could be to prompt the error log: 
```
Could not open conf file 'samples/config/ubuntu.co' (No such file or directory)
Failed to parse conf file(s), exiting.
```
and **exit** CSD with status `EXIT_FAILURE`.

Please correct me if I missing something. Thanks.

**Comment by MatejFranceskin** [comment]
Fixed with https://github.com/Dronecode/camera-manager/pull/192
