### ISSUE TITLE
Is this project still alive

### ISSUE THREAD

**Issue by kuiskas** [Dronecode/camera-manager#197]
Hello,
can someone tell if this project is still alive or if there is another alternative the community is working with?
Thanks in advance.
Albert

**Comment by hamishwillee** [comment]
@kuiskas IMO, "not very". This was contributed by Intel but is no longer used (AFAIK) by them. The lead engineer @lbegani will still answer questions and fix bugs but there is no active development.

I know of know other alternative. It would be great to have one.
